name: 'Setup Java'
description: 'Setup Java'
runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: adopt
        java-version: 17
